# **File assumed as Plant 2 is- 'Copy of PPD FY25-26'**

In [1]:
import pandas as pd

file = 'Copy of PPD FY25-26.xlsx'

xls = pd.ExcelFile(file)

xls.sheet_names

['Master',
 'Apr-25',
 'May-25',
 'Jun-2025',
 'July-2025',
 'Aug-2025',
 'Sep-2025',
 'Oct-2025',
 'Nov-2025']

In [2]:
df = pd.read_excel(file, sheet_name='Apr-25')

df.head()

,DC capacity,118.8,41.58,160.38,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Date,Inverter 1 (Wh),Inverter 2 (Wh),Actual Generation (kWh),GHI kW/m2 Sat Data,NaN,DC capacity,131.35,124.81,127.53,125.35,129.17,129.71,112.27,129.71,123.17,126.99,1260.06,NaN
1,2025-04-01 00:00:00,NaN,NaN,186,NaN,NaN,Date,Inverter 1,Inverter 2,Inverter 3,Inverter 4,Inverter 5,Inverter 6,Inverter 7,Inverter 8,Inverter 9,Inverter 10,Actual Generation (kWh),GHI kW/m2 Sat Data
2,2025-04-02 00:00:00,NaN,NaN,70,NaN,NaN,2025-04-01 00:00:00,147.09,178.8,163.6,163.9,170.2,171.4,160.81,NaN,NaN,NaN,1155.8,2.01
3,2025-04-03 00:00:00,NaN,NaN,492,NaN,NaN,2025-04-02 00:00:00,296.8,383,352.1,350.6,358.2,359.7,341.3,NaN,NaN,NaN,2441.7,4.43
4,2025-04-04 00:00:00,NaN,NaN,0,NaN,NaN,2025-04-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,826,4.95

## Extracting right-side table as analysis will be performed on Right-side table having complete plant dataset

In [4]:
df_raw = pd.read_excel(file, sheet_name='Apr-25', header=None)

In [5]:
for i in range(len(df_raw)):
    row = df_raw.iloc[i].astype(str)
    if ('Date' in row.values) and any('Inverter' in str(x) for x in row.values):
        header_row = i
        break

print("Header found at row:", header_row)

Header found at row: 1

In [6]:
for i in range(len(df_raw)):
    row = df_raw.iloc[i].astype(str)
    if ('Date' in row.values) and any('Inverter' in str(x) for x in row.values):
        header_row = i
        break

print("Header found at row:", header_row)

Header found at row: 1

In [7]:
df.columns = df.columns.astype(str).str.strip()

In [8]:
df.head()

,Date,Inverter 1 (Wh),Inverter 2 (Wh),Actual Generation (kWh),GHI kW/m2 Sat Data,Unnamed: 5,DC capacity,nan,nan,nan,nan,nan,nan,nan,129.71.1,nan,nan,nan,Unnamed: 18
0,2025-04-01 00:00:00,NaN,NaN,186.0,NaN,NaN,Date,Inverter 1,Inverter 2,Inverter 3,Inverter 4,Inverter 5,Inverter 6,Inverter 7,Inverter 8,Inverter 9,Inverter 10,Actual Generation (kWh),GHI kW/m2 Sat Data
1,2025-04-02 00:00:00,NaN,NaN,70.0,NaN,NaN,2025-04-01 00:00:00,147.09,178.8,163.6,163.9,170.2,171.4,160.81,NaN,NaN,NaN,1155.8,2.01
2,2025-04-03 00:00:00,NaN,NaN,492.0,NaN,NaN,2025-04-02 00:00:00,296.8,383,352.1,350.6,358.2,359.7,341.3,NaN,NaN,NaN,2441.7,4.43
3,2025-04-04 00:00:00,NaN,NaN,0.0,NaN,NaN,2025-04-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,826,4.95
4,2025-04-05 00:00:00,NaN,NaN,0.0,NaN,NaN,2025-04-04 00:00:00,3.9,7.7,6.2,5.2,5.1,5.8,5.5,NaN,NaN,NaN,2464,6.15

In [55]:
# Step 1: Read raw
df_raw = pd.read_excel(file, sheet_name='Apr-25', header=None)

In [58]:
# Step 2: Find RIGHT table start column
for col in range(df_raw.shape[1]):
    column_values = df_raw.iloc[:, col].astype(str)
    
    if 'Date' in column_values.values:
        print("Date found in column:", col)

Date found in column: 0
Date found in column: 6

In [57]:
# Step 3: Extract RIGHT table only
right_col = 6  # replace with second "Date" column index

df = df_raw.iloc[:, right_col:]

In [59]:
# Step 4 (find correct header row INSIDE right table)
for i in range(len(df)):
    row = df.iloc[i].astype(str)
    
    if 'Date' in row.values:
        header_row = i
        break

print("Header row inside right table:", header_row)

Header row inside right table: 2

In [60]:
# Step 5 (set correct header)
df.columns = df.iloc[header_row]
df = df[header_row + 1:]

In [61]:
# Step 6 (clean)
df.columns = df.columns.astype(str).str.strip()

print(df.columns)

Index(['Date', 'Inverter 1', 'Inverter 2', 'Inverter 3', 'Inverter 4',
       'Inverter 5', 'Inverter 6', 'Inverter 7', 'Inverter 8', 'Inverter 9',
       'Inverter 10', 'Actual Generation (kWh)', 'GHI kW/m2 Sat Data'],
      dtype='object', name=2)

In [65]:
# Step 7
df = df.copy()

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

df = df.dropna(subset=['Date'])

In [63]:
# Rename columns
df = df.rename(columns={
    'Actual Generation (kWh)': 'Generation',
    'GHI kW/m2 Sat Data': 'GHI'
})

In [21]:
# Convert all inverter + generation + GHI to numeric
for col in df.columns:
    if col != 'Date':
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [64]:
df.head()

2,Date,Inverter 1,Inverter 2,Inverter 3,Inverter 4,Inverter 5,Inverter 6,Inverter 7,Inverter 8,Inverter 9,Inverter 10,Generation,GHI
3,2025-04-01,147.09,178.8,163.6,163.9,170.2,171.4,160.81,NaN,NaN,NaN,1155.8,2.01
4,2025-04-02,296.8,383,352.1,350.6,358.2,359.7,341.3,NaN,NaN,NaN,2441.7,4.43
5,2025-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,826,4.95
6,2025-04-04,3.9,7.7,6.2,5.2,5.1,5.8,5.5,NaN,NaN,NaN,2464,6.15
7,2025-04-05,380.1,544.1,486.7,475.2,487.9,493.7,467.2,NaN,NaN,NaN,3334.9,6.03

In [23]:
df = df.reset_index(drop=True)

In [24]:
df.head()

2,Date,Inverter 1,Inverter 2,Inverter 3,Inverter 4,Inverter 5,Inverter 6,Inverter 7,Inverter 8,Inverter 9,Inverter 10,Generation,GHI
0,2025-04-01,147.09,178.8,163.6,163.9,170.2,171.4,160.81,NaN,NaN,NaN,1155.8,2.01
1,2025-04-02,296.80,383.0,352.1,350.6,358.2,359.7,341.30,NaN,NaN,NaN,2441.7,4.43
2,2025-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,826.0,4.95
3,2025-04-04,3.90,7.7,6.2,5.2,5.1,5.8,5.50,NaN,NaN,NaN,2464.0,6.15
4,2025-04-05,380.10,544.1,486.7,475.2,487.9,493.7,467.20,NaN,NaN,NaN,3334.9,6.03

## Basic KPIs for April

### **Benchmark**- CUF Range and Interpretation
### 14–18% -Good
### 10–14% -Average
### <10%   -Poor

In [51]:
# Total generation
total_gen = df['Generation'].sum()

days = len(df)

print("Total Generation:", total_gen)
print("Total Days:", days)

Total Generation: 115955.16
Total Days: 30

In [54]:
# CUF
capacity = 1260

cuf = total_gen / (capacity * 24 * days)

print("CUF:", cuf)

CUF: 0.1278165343915344

In [53]:
# Correlation
df[['GHI', 'Generation']].corr()

1                GHI  Generation
1
GHI         1.000000    0.963465
Generation  0.963465    1.000000

### Checking the reason if this is due to downtime

In [29]:
downtime_days = df[
    (df['Generation'] < 2000) | (df['Generation'].isna())
].copy()

len(downtime_days)

3

In [30]:
downtime_days[['Date', 'GHI', 'Generation']]

2       Date   GHI  Generation
0 2025-04-01  2.01     1155.80
2 2025-04-03  4.95      826.00
7 2025-04-08  5.19     1970.29

In [31]:
df.count()

2
Date           30
Inverter 1     29
Inverter 2     29
Inverter 3     29
Inverter 4     29
Inverter 5     29
Inverter 6     29
Inverter 7     29
Inverter 8      0
Inverter 9      0
Inverter 10     0
Generation     30
GHI            30
dtype: int64

## Calculate % active capacity

In [32]:
active_inverters = 7
total_inverters = 10

active_percent = active_inverters / total_inverters

print(active_percent)

0.7

## Adjusted analysis if all the inverters worked

In [33]:
adjusted_gen = total_gen / active_percent

print(adjusted_gen)

125038.89999999998

In [34]:
adjusted_cuf = adjusted_gen / (capacity * 24 * days)
print(adjusted_cuf)

0.13782947530864195

### Note- Approximately 30% of installed capacity (3 out of 10 inverters) remained inactive throughout April, resulting in an estimated energy loss of  approx 37.5 MWh. This is the primary driver of reduced CUF (~9.6%).

## Automating same across all months of plant 2

In [36]:
monthly_sheets = [
    'Apr-25', 'May-25', 'Jun-2025', 'July-2025',
    'Aug-2025', 'Sep-2025', 'Oct-2025', 'Nov-2025'
]

In [50]:
summary = []

for sheet in monthly_sheets:
    
    # extract right side table for analysis
    df_raw = pd.read_excel(file, sheet_name=sheet, header=None)
    
    # find right table start column
    date_cols = []
    for col in range(df_raw.shape[1]):
        if 'Date' in df_raw.iloc[:, col].astype(str).values:
            date_cols.append(col)
    
    right_col = date_cols[-1]
    df = df_raw.iloc[:, right_col:]
    
    # find header row
    for i in range(len(df)):
        if 'Date' in df.iloc[i].astype(str).values:
            header_row = i
            break
    
    df.columns = df.iloc[header_row]
    df = df[header_row + 1:]
    
    df.columns = df.columns.astype(str).str.strip()
    df = df.copy()
    
    # rename
    df = df.rename(columns={
        'Actual Generation (kWh)': 'Generation',
        'GHI kW/m2 Sat Data': 'GHI'
    })
    
    # convert numeric
    for col in df.columns:
        if col != 'Date':
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df = df.dropna(subset=['Date'])
    
    # KPI
    total_gen = df['Generation'].sum()
    days = len(df)
    
    capacity = 1260  # confirm once
    cuf = total_gen / (capacity * 24 * days)

    # Approximate PR since GHI is available
    pr = total_gen / (df['GHI'].sum() * capacity)
    
    # active inverters
    inverter_cols = [col for col in df.columns if 'Inverter' in col]
    active_inv = df[inverter_cols].count().gt(0).sum()
    
    total_inv = len(inverter_cols)

    # Underperformance days
    underperf_days = df[df['Generation'] < 2000]

    num_underperf = len(underperf_days)

    # Classify using GHI
    underperf_days = underperf_days.copy()

    underperf_days['Reason'] = underperf_days['GHI'].apply(
      lambda x: 'Weather' if x < 3 else 'System'
    )

    weather_days = len(underperf_days[underperf_days['Reason'] == 'Weather'])
    system_days = len(underperf_days[underperf_days['Reason'] == 'System'])
    
    summary.append({
        'Month': sheet,
        'Generation': total_gen,
        'CUF': cuf,
        'PR': pr,
        'Active Inverters': active_inv,
        'Total Inverters': total_inv,
        'Underperformance Days': num_underperf,
        'System Issue Days': system_days,
        'Weather Issue Days': weather_days,
    })

    summary_df = pd.DataFrame(summary)

In [66]:
summary_df

,Month,Generation,CUF,PR,Active Inverters,Total Inverters,Underperformance Days,System Issue Days,Weather Issue Days
0,Apr-25,87527.23,0.096481,0.418445,7,10,3,2,1
1,May-25,91590.71,0.097703,0.491322,7,10,4,1,3
2,Jun-2025,100956.81,0.111284,0.723014,10,10,9,2,7
3,July-2025,86312.08,0.092072,0.798016,10,10,11,0,11
4,Aug-2025,92137.24,0.098286,0.782586,10,10,2,0,2
5,Sep-2025,83824.02,0.092399,0.787581,10,10,8,0,8
6,Oct-2025,120193.60,0.128215,0.744143,10,10,1,0,1
7,Nov-2025,115955.16,0.127817,0.719868,10,10,0,0,0